import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const neuropal = localFont({
  src: "../fonts/Neuropol.ttf",
  variable: "--neuropal",
});
const clashdisplay = localFont({
  src: "../fonts/ClashDisplay-Variable.ttf",
  variable: "--clashdisplay",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${neuropal.variable} ${clashdisplay.variable}`}>
        {children}
      </body>
    </html>
  );
}
