import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["500", "400", "300"] });

const neuropal = localFont({
  src: "../fonts/NEUROPOL.ttf",
  variable: "--neuropal",
});
const clashdisplay = localFont({
  src: "../fonts/ClashDisplay-Variable.ttf",
  variable: "--clashdisplay",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${neuropal.variable} ${clashdisplay.variable} ${poppins.className}`}
      >
        {children}
      </body>
    </html>
  );
}
